# Generated by Django 3.2.9 on 2021-11-13 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(db_index=True)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('gift_note', models.TextField(help_text='Description of what the recipient would like')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_created_by', to=settings.AUTH_USER_MODEL)),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawings.drawing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DrawingResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawing_giver', to='drawings.participant')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawing_recipient', to='drawings.participant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
