# Generated by Django 3.2.9 on 2021-11-15 04:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='status',
            field=models.CharField(choices=[('Waiting To Begin', 'Waiting To Begin'), ('Gathering Participants', 'Gathering Participants'), ('Underway', 'Underway'), ('Concluded', 'Concluded')], default='Waiting To Begin', max_length=32),
        ),
        migrations.AddField(
            model_name='participant',
            name='exclusion_reason',
            field=models.TextField(blank=True, help_text='Reason for exclusion preferences, in case this needs to be manually overridden', null=True),
        ),
        migrations.CreateModel(
            name='DrawingOmissionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='omission_giver', to='drawings.participant')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='omission_recipient', to='drawings.participant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
