# Generated by Django 3.2.9 on 2021-11-21 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0002_auto_20211115_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawingresult',
            name='drawing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='drawing_result_drawing', to='drawings.drawing'),
            preserve_default=False,
        ),
    ]
