# Generated by Django 3.2.9 on 2021-11-21 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0003_drawingresult_drawing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='user',
        ),
    ]
